### Get all messages
GET http://localhost:3000/messages


### Create message
POST http://localhost:3000/messages
content-type: application/json

{
    "content": "Hi there!"
}


### Get single message
GET http://localhost:3000/messages/1234