### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test@xyz.com",
    "password": "1234"
}

### Signin to existing user

POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test@xyz.com",
    "password": "1234"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Get the currently signed in user - custom decorator
GET http://localhost:3000/auth/whoami2

### Sign out user
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID

GET http://localhost:3000/auth/2


### Find all users with given email

GET http://localhost:3000/auth?email=akshaya@gmail.com


### Delete user with id
DELETE http://localhost:3000/auth/3

### Update user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "akshaya@gmail.com"
}